import type { Appointment, ServiceOption } from '../types/appointment.types';

export const mockServices: ServiceOption[] = [
  { id: 'srv-1', name: 'Consulta Dermatológica', category: 'Dermatología', durationMinutes: 30, price: 120000 },
  { id: 'srv-2', name: 'Medicina General', category: 'Medicina General', durationMinutes: 30, price: 80000 },
  { id: 'srv-3', name: 'Neurología', category: 'Neurología', durationMinutes: 45, price: 150000 },
  { id: 'srv-4', name: 'Chequeo Preventivo', category: 'Medicina General', durationMinutes: 60, price: 200000 },
  { id: 'srv-5', name: 'Consulta Pediatría', category: 'Pediatría', durationMinutes: 30, price: 90000 },
];

export const AVAILABLE_TIME_SLOTS = [
  '08:00 AM',
  '08:30 AM',
  '09:00 AM',
  '09:30 AM',
  '10:00 AM',
  '10:30 AM',
  '11:00 AM',
  '11:30 AM',
  '01:00 PM',
  '01:30 PM',
  '02:00 PM',
  '02:30 PM',
  '03:00 PM',
  '03:30 PM',
  '04:00 PM',
  '04:30 PM',
  '05:00 PM',
];

export const mockAppointments: Appointment[] = [
  {
    id: 1,
    patientId: 1,
    patientName: 'Maria Rodriguez',
    patientAge: 34,
    patientGender: 'Femenino',
    patientDoc: 'CC-1029384756',
    patientPhone: '+57 300 123 4567',
    patientEmail: 'mrodriguez@email.com',
    patientAvatarBg: '#0A9396',
    patientInitials: 'MR',
    professionalId: 'prof-1',
    professionalName: 'Dr. Ramírez',
    professionalSpecialty: 'Dermatología',
    serviceId: 'srv-1',
    serviceName: 'Consulta Dermatológica',
    date: '2026-10-28',
    time: '10:00 AM',
    status: 'Agendada',
    notes: 'Revisión de lunar en brazo derecho',
  },
  {
    id: 2,
    patientId: 2,
    patientName: 'Juan Gomez',
    patientAge: 45,
    patientGender: 'Masculino',
    patientDoc: 'CE-987654321',
    patientPhone: '+57 310 987 6543',
    patientEmail: 'jgomez@email.com',
    patientAvatarBg: '#005F73',
    patientInitials: 'JG',
    professionalId: 'prof-3',
    professionalName: 'Dra. Smith',
    professionalSpecialty: 'Medicina General',
    serviceId: 'srv-2',
    serviceName: 'Medicina General',
    date: '2026-10-28',
    time: '11:30 AM',
    status: 'Atendida',
    notes: 'Control de hipertensión',
  },
  {
    id: 3,
    patientId: 3,
    patientName: 'Ana Garcia',
    patientAge: 29,
    patientGender: 'Femenino',
    patientDoc: 'CC-1092837465',
    patientPhone: '+57 301 456 7890',
    patientEmail: 'agarcia@email.com',
    patientAvatarBg: '#9B5DE5',
    patientInitials: 'AG',
    professionalId: 'prof-1',
    professionalName: 'Dr. Ramírez',
    professionalSpecialty: 'Dermatología',
    serviceId: 'srv-1',
    serviceName: 'Consulta Dermatológica',
    date: '2026-10-28',
    time: '01:00 PM',
    status: 'Cancelada',
    notes: 'Canceló por motivos de trabajo',
  },
  {
    id: 4,
    patientId: 4,
    patientName: 'Roberto Chen',
    patientAge: 52,
    patientGender: 'Masculino',
    patientDoc: 'CC-79845123',
    patientPhone: '+57 315 234 5678',
    patientEmail: 'rchen@email.com',
    patientAvatarBg: '#EE6C4D',
    patientInitials: 'RC',
    professionalId: 'prof-4',
    professionalName: 'Dr. Evans',
    professionalSpecialty: 'Neurología',
    serviceId: 'srv-3',
    serviceName: 'Neurología',
    date: '2026-10-28',
    time: '02:30 PM',
    status: 'No asistió',
    notes: 'No respondió al llamado ni confirmó cita',
  },
  {
    id: 5,
    patientId: 5,
    patientName: 'Carlos Mendoza',
    patientAge: 38,
    patientGender: 'Masculino',
    patientDoc: 'CC-80123987',
    patientPhone: '+57 320 876 5432',
    patientEmail: 'cmendoza@email.com',
    patientAvatarBg: '#2A9D8F',
    patientInitials: 'CM',
    professionalId: 'prof-2',
    professionalName: 'Dra. María Gonzales',
    professionalSpecialty: 'Medicina General',
    serviceId: 'srv-4',
    serviceName: 'Chequeo Preventivo',
    date: '2026-10-28',
    time: '04:00 PM',
    status: 'Agendada',
    notes: 'Exámenes de laboratorio anuales',
  },
  {
    id: 6,
    patientId: 1,
    patientName: 'Maria Rodriguez',
    patientAge: 34,
    patientGender: 'Femenino',
    patientDoc: 'CC-1029384756',
    patientPhone: '+57 300 123 4567',
    patientEmail: 'mrodriguez@email.com',
    patientAvatarBg: '#0A9396',
    patientInitials: 'MR',
    professionalId: 'prof-1',
    professionalName: 'Dr. Ramírez',
    professionalSpecialty: 'Dermatología',
    serviceId: 'srv-1',
    serviceName: 'Consulta Dermatológica',
    date: '2026-10-12',
    time: '10:00 AM',
    status: 'Atendida',
    notes: 'Revisión preventiva',
  },
  {
    id: 7,
    patientId: 2,
    patientName: 'Juan Gomez',
    patientAge: 45,
    patientGender: 'Masculino',
    patientDoc: 'CE-987654321',
    patientPhone: '+57 310 987 6543',
    patientEmail: 'jgomez@email.com',
    patientAvatarBg: '#005F73',
    patientInitials: 'JG',
    professionalId: 'prof-3',
    professionalName: 'Dra. Smith',
    professionalSpecialty: 'Medicina General',
    serviceId: 'srv-2',
    serviceName: 'Medicina General',
    date: '2026-10-15',
    time: '09:30 AM',
    status: 'Agendada',
  },
  {
    id: 8,
    patientId: 3,
    patientName: 'Ana Garcia',
    patientAge: 29,
    patientGender: 'Femenino',
    patientDoc: 'CC-1092837465',
    patientPhone: '+57 301 456 7890',
    patientEmail: 'agarcia@email.com',
    patientAvatarBg: '#9B5DE5',
    patientInitials: 'AG',
    professionalId: 'prof-2',
    professionalName: 'Dra. María Gonzales',
    professionalSpecialty: 'Medicina General',
    serviceId: 'srv-2',
    serviceName: 'Medicina General',
    date: '2026-10-17',
    time: '11:00 AM',
    status: 'Agendada',
  },
  {
    id: 9,
    patientId: 4,
    patientName: 'Roberto Chen',
    patientAge: 52,
    patientGender: 'Masculino',
    patientDoc: 'CC-79845123',
    patientPhone: '+57 315 234 5678',
    patientEmail: 'rchen@email.com',
    patientAvatarBg: '#EE6C4D',
    patientInitials: 'RC',
    professionalId: 'prof-4',
    professionalName: 'Dr. Evans',
    professionalSpecialty: 'Neurología',
    serviceId: 'srv-3',
    serviceName: 'Neurología',
    date: '2026-10-23',
    time: '03:00 PM',
    status: 'Agendada',
  },
  {
    id: 10,
    patientId: 5,
    patientName: 'Carlos Mendoza',
    patientAge: 38,
    patientGender: 'Masculino',
    patientDoc: 'CC-80123987',
    patientPhone: '+57 320 876 5432',
    patientEmail: 'cmendoza@email.com',
    patientAvatarBg: '#2A9D8F',
    patientInitials: 'CM',
    professionalId: 'prof-5',
    professionalName: 'Dr. Martínez',
    professionalSpecialty: 'Pediatría',
    serviceId: 'srv-5',
    serviceName: 'Consulta Pediatría',
    date: '2026-10-30',
    time: '08:30 AM',
    status: 'Agendada',
  },
];

/**
 * Validates whether a professional already has an active appointment at the given date & time slot.
 * Returns the conflicting appointment if found, or undefined if clear.
 */
export const checkScheduleConflict = (
  appointments: Appointment[],
  professionalId: string,
  date: string,
  time: string,
  excludeAppointmentId?: number
): Appointment | undefined => {
  return appointments.find(
    (app) =>
      app.professionalId === professionalId &&
      app.date === date &&
      app.time === time &&
      app.status !== 'Cancelada' &&
      app.id !== excludeAppointmentId
  );
};
