import type { Patient } from '../types/patient.types';

export const mockPatients: Patient[] = [
  {
    id: 1,
    name: 'Maria Rodriguez',
    gender: 'Femenino',
    age: 34,
    documentType: 'CC',
    documentNumber: '1029384756',
    contact: {
      phone: '+57 300 123 4567',
      email: 'mrodriguez@email.com',
      address: 'Calle 123 #45-67, Apto 302',
    },
    lastVisitDate: '12 Oct 2023',
    lastVisitSpecialty: 'Dermatología',
    specialtyBadgeColor: 'purple',
    status: 'active',
    initials: 'MR',
    avatarBg: '#0A9396',
    medicalData: {
      bloodType: 'O+',
      allergies: ['Penicilina'],
      chronicConditions: ['Rinitis alérgica'],
    },
    recentActivity: [
      {
        id: 101,
        title: 'Consulta Dermatología',
        date: '12 Oct 2023',
        doctor: 'Dr. Ramírez',
        note: 'Revisión lunar sospechoso en brazo derecho. Se programa biopsia.',
        category: 'consulta',
      },
      {
        id: 102,
        title: 'Laboratorios Clínicos',
        date: '05 Sep 2023',
        category: 'laboratorio',
      },
    ],
    history: [
      {
        id: 201,
        date: '12 Oct 2023',
        specialty: 'Dermatología',
        doctor: 'Dr. Ramírez',
        diagnosis: 'Dermatitis atópica severa',
      },
      {
        id: 202,
        date: '05 Sep 2023',
        specialty: 'Medicina General',
        doctor: 'Dra. María Gonzales',
        diagnosis: 'Chequeo anual preventivo completo',
      },
    ],
    notes: [
      {
        id: 301,
        date: '12 Oct 2023',
        author: 'Dr. Ramírez',
        text: 'Paciente refiere prurito nocturno en extremidades superiores.',
      },
    ],
  },
  {
    id: 2,
    name: 'Juan Gomez',
    gender: 'Masculino',
    age: 45,
    documentType: 'CE',
    documentNumber: '987654321',
    contact: {
      phone: '+57 310 987 6543',
      email: 'jgomez@email.com',
      address: 'Carrera 15 #88-21, Piso 4',
    },
    lastVisitDate: '05 Sep 2023',
    lastVisitSpecialty: 'Medicina General',
    specialtyBadgeColor: 'green',
    status: 'active',
    initials: 'JG',
    avatarBg: '#64748B',
    medicalData: {
      bloodType: 'A+',
      allergies: ['Ninguna'],
      chronicConditions: ['Hipertensión leve'],
    },
    recentActivity: [
      {
        id: 103,
        title: 'Consulta Medicina General',
        date: '05 Sep 2023',
        doctor: 'Dra. María Gonzales',
        note: 'Monitoreo de presión arterial. Valores dentro del rango normal (120/80).',
        category: 'consulta',
      },
    ],
    history: [
      {
        id: 203,
        date: '05 Sep 2023',
        specialty: 'Medicina General',
        doctor: 'Dra. María Gonzales',
        diagnosis: 'Control hipertensivo de rutina',
      },
    ],
    notes: [
      {
        id: 302,
        date: '05 Sep 2023',
        author: 'Dra. María Gonzales',
        text: 'Se sugiere continuar con dieta hiposódica y caminata diaria.',
      },
    ],
  },
  {
    id: 3,
    name: 'Maria Rodriguez',
    gender: 'Femenino',
    age: 34,
    documentType: 'CC',
    documentNumber: '1029384756',
    contact: {
      phone: '+57 300 123 4567',
      email: 'mrodriguez@email.com',
      address: 'Calle 123 #45-67, Apto 302',
    },
    lastVisitDate: '12 Oct 2023',
    lastVisitSpecialty: 'Dermatología',
    specialtyBadgeColor: 'purple',
    status: 'active',
    initials: 'MR',
    avatarBg: '#0A9396',
    medicalData: {
      bloodType: 'O+',
      allergies: ['Penicilina'],
    },
    recentActivity: [],
    history: [],
    notes: [],
  },
  {
    id: 4,
    name: 'Maria Rodriguez',
    gender: 'Femenino',
    age: 34,
    documentType: 'CC',
    documentNumber: '1029384756',
    contact: {
      phone: '+57 300 123 4567',
      email: 'mrodriguez@email.com',
      address: 'Calle 123 #45-67, Apto 302',
    },
    lastVisitDate: '12 Oct 2023',
    lastVisitSpecialty: 'Dermatología',
    specialtyBadgeColor: 'purple',
    status: 'active',
    initials: 'MR',
    avatarBg: '#0A9396',
    medicalData: {
      bloodType: 'O+',
      allergies: ['Penicilina'],
    },
    recentActivity: [],
    history: [],
    notes: [],
  },
  {
    id: 5,
    name: 'Maria Rodriguez',
    gender: 'Femenino',
    age: 34,
    documentType: 'CE',
    documentNumber: '987654321',
    contact: {
      phone: '+57 310 987 6543',
      email: 'jgomez@email.com',
      address: 'Av. Las Palmas 45',
    },
    lastVisitDate: '12 Oct 2023',
    lastVisitSpecialty: 'Dermatología',
    specialtyBadgeColor: 'purple',
    status: 'active',
    initials: 'JG',
    avatarBg: '#8B5CF6',
    medicalData: {
      bloodType: 'B+',
      allergies: ['Aspirina'],
    },
    recentActivity: [],
    history: [],
    notes: [],
  },
  {
    id: 6,
    name: 'Juan Gomez',
    gender: 'Masculino',
    age: 45,
    documentType: 'CE',
    documentNumber: '987654321',
    contact: {
      phone: '+57 300 123 4567',
      email: 'jgomez@email.com',
      address: 'Carrera 15 #88-21',
    },
    lastVisitDate: '12 Oct 2023',
    lastVisitSpecialty: 'Dermatología',
    specialtyBadgeColor: 'purple',
    status: 'active',
    initials: 'JG',
    avatarBg: '#3B82F6',
    medicalData: {
      bloodType: 'O-',
      allergies: ['Ninguna'],
    },
    recentActivity: [],
    history: [],
    notes: [],
  },
  {
    id: 7,
    name: 'Maria Rodriguez',
    gender: 'Femenino',
    age: 45,
    documentType: 'CE',
    documentNumber: '987654321',
    contact: {
      phone: '+57 300 123 4567',
      email: 'mrodriguez@email.com',
      address: 'Calle 10 #12-40',
    },
    lastVisitDate: '12 Oct 2023',
    lastVisitSpecialty: 'Dermatología',
    specialtyBadgeColor: 'purple',
    status: 'active',
    initials: 'JG',
    avatarBg: '#F59E0B',
    medicalData: {
      bloodType: 'AB+',
      allergies: ['Sulfa'],
    },
    recentActivity: [],
    history: [],
    notes: [],
  },
  {
    id: 8,
    name: 'Juan Gomez',
    gender: 'Masculino',
    age: 45,
    documentType: 'CC',
    documentNumber: '1029384756',
    contact: {
      phone: '+57 300 123 4587',
      email: 'jgomez@email.com',
      address: 'Calle 5 #3-12',
    },
    lastVisitDate: '13 Oct 2023',
    lastVisitSpecialty: 'Medicina General',
    specialtyBadgeColor: 'green',
    status: 'active',
    initials: 'JG',
    avatarBg: '#10B981',
    medicalData: {
      bloodType: 'O+',
      allergies: ['Ninguna'],
    },
    recentActivity: [],
    history: [],
    notes: [],
  },
];
