import type { Professional } from './profesional.types';

export const initialProfesionales: Professional[] = [
  {
    id: 'prof-1',
    nombre: 'Sarah',
    apellido: 'Jenkins',
    tituloPrefix: 'Dra.',
    especialidad: 'Cardiología Intervencionista',
    subespecialidad: 'Cardiología',
    registroProfesional: 'CMP-45892',
    consultorio: 'Consultorio 302',
    estado: 'Activo',
    citasHoy: 12,
    disponibleHoy: true,
    foto: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80',
    telefono: '+51 987 654 321',
    email: 'sjenkins@healtlab.com',
    disponibilidad: [
      { dia: 'LUN', diaNombre: 'Lunes', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: true },
      { dia: 'LUN', diaNombre: 'Lunes', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: true },
      { dia: 'MAR', diaNombre: 'Martes', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: true },
      { dia: 'MAR', diaNombre: 'Martes', jornada: 'Tarde', horaInicio: '14:00', horaFin: '19:00', activo: false },
      { dia: 'MIÉ', diaNombre: 'Miércoles', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: true },
      { dia: 'MIÉ', diaNombre: 'Miércoles', jornada: 'Tarde', horaInicio: '14:00', horaFin: '19:00', activo: true },
      { dia: 'JUE', diaNombre: 'Jueves', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: false },
      { dia: 'JUE', diaNombre: 'Jueves', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: true },
      { dia: 'VIE', diaNombre: 'Viernes', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: true },
      { dia: 'VIE', diaNombre: 'Viernes', jornada: 'Tarde', horaInicio: '14:00', horaFin: '19:00', activo: true },
      { dia: 'SÁB', diaNombre: 'Sábado', jornada: 'Mañana', horaInicio: '09:00', horaFin: '12:30', activo: false },
      { dia: 'SÁB', diaNombre: 'Sábado', jornada: 'Tarde', horaInicio: '14:00', horaFin: '17:00', activo: false },
      { dia: 'DOM', diaNombre: 'Domingo', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: false },
      { dia: 'DOM', diaNombre: 'Domingo', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: false },
    ],
    citas: [
      {
        id: 'cita-101',
        pacienteNombre: 'María López',
        motivoConsulta: 'Consulta Cardiológica',
        diaAbrev: 'LUN',
        fecha: '2026-08-10',
        horaInicio: '08:00',
        horaFin: '09:00',
        estado: 'Atendida',
        consultorio: 'Consultorio 302',
      },
      {
        id: 'cita-102',
        pacienteNombre: 'Carlos Mendoza',
        motivoConsulta: 'Ecocardiograma',
        diaAbrev: 'LUN',
        fecha: '2026-08-10',
        horaInicio: '10:00',
        horaFin: '11:00',
        estado: 'Atendida',
        consultorio: 'Consultorio 302',
      },
      {
        id: 'cita-103',
        pacienteNombre: 'Ana Gómez',
        motivoConsulta: 'Evaluación Preoperatoria',
        diaAbrev: 'MAR',
        fecha: '2026-08-11',
        horaInicio: '09:00',
        horaFin: '10:00',
        estado: 'Confirmada',
        consultorio: 'Consultorio 302',
      },
      {
        id: 'cita-104',
        pacienteNombre: 'Pedro Ramírez',
        motivoConsulta: 'Prueba de Esfuerzo',
        diaAbrev: 'MIÉ',
        fecha: '2026-08-12',
        horaInicio: '08:00',
        horaFin: '09:30',
        estado: 'Confirmada',
        consultorio: 'Consultorio 302',
      },
      {
        id: 'cita-105',
        pacienteNombre: 'Lucía Fernández',
        motivoConsulta: 'Control de Arritmias',
        diaAbrev: 'MIÉ',
        fecha: '2026-08-12',
        horaInicio: '14:00',
        horaFin: '15:00',
        estado: 'Pendiente',
        consultorio: 'Consultorio 302',
      },
      {
        id: 'cita-106',
        pacienteNombre: 'Roberto Silva',
        motivoConsulta: 'Consulta de Seguimiento',
        diaAbrev: 'JUE',
        fecha: '2026-08-13',
        horaInicio: '15:00',
        horaFin: '16:00',
        estado: 'Confirmada',
        consultorio: 'Consultorio 302',
      },
      {
        id: 'cita-107',
        pacienteNombre: 'Carmen Vargas',
        motivoConsulta: 'Ecocardiograma Doppler',
        diaAbrev: 'VIE',
        fecha: '2026-08-14',
        horaInicio: '09:00',
        horaFin: '10:30',
        estado: 'Confirmada',
        consultorio: 'Consultorio 302',
      },
      {
        id: 'cita-108',
        pacienteNombre: 'Jorge Huamán',
        motivoConsulta: 'Consulta Cardiológica',
        diaAbrev: 'VIE',
        fecha: '2026-08-14',
        horaInicio: '16:00',
        horaFin: '17:00',
        estado: 'Confirmada',
        consultorio: 'Consultorio 302',
      },
    ],
  },
  {
    id: 'prof-2',
    nombre: 'Marcus',
    apellido: 'Rivera',
    tituloPrefix: 'Dr.',
    especialidad: 'Medicina General',
    subespecialidad: 'Medicina General',
    registroProfesional: 'CMP-38102',
    consultorio: 'Consultorio 105',
    estado: 'Activo',
    citasHoy: 0,
    disponibleHoy: false,
    foto: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80',
    telefono: '+51 987 112 233',
    email: 'mrivera@healtlab.com',
    disponibilidad: [
      { dia: 'LUN', diaNombre: 'Lunes', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: true },
      { dia: 'LUN', diaNombre: 'Lunes', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: true },
      { dia: 'MAR', diaNombre: 'Martes', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: true },
      { dia: 'MAR', diaNombre: 'Martes', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: true },
      { dia: 'MIÉ', diaNombre: 'Miércoles', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: false },
      { dia: 'MIÉ', diaNombre: 'Miércoles', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: false },
      { dia: 'JUE', diaNombre: 'Jueves', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: true },
      { dia: 'JUE', diaNombre: 'Jueves', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: true },
      { dia: 'VIE', diaNombre: 'Viernes', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: true },
      { dia: 'VIE', diaNombre: 'Viernes', jornada: 'Tarde', horaInicio: '14:00', horaFin: '17:00', activo: true },
      { dia: 'SÁB', diaNombre: 'Sábado', jornada: 'Mañana', horaInicio: '09:00', horaFin: '12:00', activo: false },
      { dia: 'SÁB', diaNombre: 'Sábado', jornada: 'Tarde', horaInicio: '14:00', horaFin: '17:00', activo: false },
      { dia: 'DOM', diaNombre: 'Domingo', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: false },
      { dia: 'DOM', diaNombre: 'Domingo', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: false },
    ],
    citas: [
      {
        id: 'cita-201',
        pacienteNombre: 'Rosa Benítez',
        motivoConsulta: 'Consulta Medicina General',
        diaAbrev: 'LUN',
        fecha: '2026-08-10',
        horaInicio: '09:00',
        horaFin: '10:00',
        estado: 'Atendida',
        consultorio: 'Consultorio 105',
      },
      {
        id: 'cita-202',
        pacienteNombre: 'Gonzalo Morales',
        motivoConsulta: 'Chequeo Preventivo Completo',
        diaAbrev: 'MAR',
        fecha: '2026-08-11',
        horaInicio: '10:00',
        horaFin: '11:00',
        estado: 'Confirmada',
        consultorio: 'Consultorio 105',
      },
      {
        id: 'cita-203',
        pacienteNombre: 'Elena Torres',
        motivoConsulta: 'Certificado Médico de Salud',
        diaAbrev: 'VIE',
        fecha: '2026-08-14',
        horaInicio: '15:00',
        horaFin: '16:00',
        estado: 'Confirmada',
        consultorio: 'Consultorio 105',
      },
    ],
  },
  {
    id: 'prof-3',
    nombre: 'Alan',
    apellido: 'Chen',
    tituloPrefix: 'Dr.',
    especialidad: 'Pediatría',
    subespecialidad: 'Pediatría',
    registroProfesional: 'CMP-51204',
    consultorio: 'Consultorio 204',
    estado: 'Activo',
    citasHoy: 8,
    disponibleHoy: true,
    foto: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80',
    telefono: '+51 987 334 455',
    email: 'achen@healtlab.com',
    disponibilidad: [
      { dia: 'LUN', diaNombre: 'Lunes', jornada: 'Mañana', horaInicio: '08:00', horaFin: '12:30', activo: true },
      { dia: 'LUN', diaNombre: 'Lunes', jornada: 'Tarde', horaInicio: '14:00', horaFin: '17:30', activo: true },
      { dia: 'MAR', diaNombre: 'Martes', jornada: 'Mañana', horaInicio: '08:00', horaFin: '12:30', activo: true },
      { dia: 'MAR', diaNombre: 'Martes', jornada: 'Tarde', horaInicio: '14:00', horaFin: '17:30', activo: true },
      { dia: 'MIÉ', diaNombre: 'Miércoles', jornada: 'Mañana', horaInicio: '08:00', horaFin: '12:30', activo: true },
      { dia: 'MIÉ', diaNombre: 'Miércoles', jornada: 'Tarde', horaInicio: '14:00', horaFin: '17:30', activo: true },
      { dia: 'JUE', diaNombre: 'Jueves', jornada: 'Mañana', horaInicio: '08:00', horaFin: '12:30', activo: true },
      { dia: 'JUE', diaNombre: 'Jueves', jornada: 'Tarde', horaInicio: '14:00', horaFin: '17:30', activo: true },
      { dia: 'VIE', diaNombre: 'Viernes', jornada: 'Mañana', horaInicio: '08:00', horaFin: '12:30', activo: true },
      { dia: 'VIE', diaNombre: 'Viernes', jornada: 'Tarde', horaInicio: '14:00', horaFin: '17:30', activo: false },
      { dia: 'SÁB', diaNombre: 'Sábado', jornada: 'Mañana', horaInicio: '09:00', horaFin: '13:00', activo: true },
      { dia: 'SÁB', diaNombre: 'Sábado', jornada: 'Tarde', horaInicio: '14:00', horaFin: '17:00', activo: false },
      { dia: 'DOM', diaNombre: 'Domingo', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: false },
      { dia: 'DOM', diaNombre: 'Domingo', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: false },
    ],
    citas: [
      {
        id: 'cita-301',
        pacienteNombre: 'Mateo Quispe',
        motivoConsulta: 'Control Niños Sanos',
        diaAbrev: 'LUN',
        fecha: '2026-08-10',
        horaInicio: '08:30',
        horaFin: '09:30',
        estado: 'Atendida',
        consultorio: 'Consultorio 204',
      },
      {
        id: 'cita-302',
        pacienteNombre: 'Sofia Castro',
        motivoConsulta: 'Evaluación de Vacunación',
        diaAbrev: 'MIÉ',
        fecha: '2026-08-12',
        horaInicio: '10:00',
        horaFin: '11:00',
        estado: 'Confirmada',
        consultorio: 'Consultorio 204',
      },
      {
        id: 'cita-303',
        pacienteNombre: 'Lucas Paredes',
        motivoConsulta: 'Consulta Pediátrica',
        diaAbrev: 'JUE',
        fecha: '2026-08-13',
        horaInicio: '14:30',
        horaFin: '15:30',
        estado: 'Confirmada',
        consultorio: 'Consultorio 204',
      },
    ],
  },
  {
    id: 'prof-4',
    nombre: 'Elena',
    apellido: 'Rostova',
    tituloPrefix: 'Dra.',
    especialidad: 'Neurología',
    subespecialidad: 'Neurología',
    registroProfesional: 'CMP-62910',
    consultorio: 'Consultorio 410',
    estado: 'Activo',
    citasHoy: 4,
    disponibleHoy: true,
    foto: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=300&auto=format&fit=crop&q=80',
    telefono: '+51 987 556 677',
    email: 'erostova@healtlab.com',
    disponibilidad: [
      { dia: 'LUN', diaNombre: 'Lunes', jornada: 'Mañana', horaInicio: '09:00', horaFin: '13:00', activo: true },
      { dia: 'LUN', diaNombre: 'Lunes', jornada: 'Tarde', horaInicio: '15:00', horaFin: '19:00', activo: true },
      { dia: 'MAR', diaNombre: 'Martes', jornada: 'Mañana', horaInicio: '09:00', horaFin: '13:00', activo: true },
      { dia: 'MAR', diaNombre: 'Martes', jornada: 'Tarde', horaInicio: '15:00', horaFin: '19:00', activo: false },
      { dia: 'MIÉ', diaNombre: 'Miércoles', jornada: 'Mañana', horaInicio: '09:00', horaFin: '13:00', activo: true },
      { dia: 'MIÉ', diaNombre: 'Miércoles', jornada: 'Tarde', horaInicio: '15:00', horaFin: '19:00', activo: true },
      { dia: 'JUE', diaNombre: 'Jueves', jornada: 'Mañana', horaInicio: '09:00', horaFin: '13:00', activo: false },
      { dia: 'JUE', diaNombre: 'Jueves', jornada: 'Tarde', horaInicio: '15:00', horaFin: '19:00', activo: true },
      { dia: 'VIE', diaNombre: 'Viernes', jornada: 'Mañana', horaInicio: '09:00', horaFin: '13:00', activo: true },
      { dia: 'VIE', diaNombre: 'Viernes', jornada: 'Tarde', horaInicio: '15:00', horaFin: '19:00', activo: true },
      { dia: 'SÁB', diaNombre: 'Sábado', jornada: 'Mañana', horaInicio: '09:00', horaFin: '13:00', activo: false },
      { dia: 'SÁB', diaNombre: 'Sábado', jornada: 'Tarde', horaInicio: '14:00', horaFin: '17:00', activo: false },
      { dia: 'DOM', diaNombre: 'Domingo', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: false },
      { dia: 'DOM', diaNombre: 'Domingo', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: false },
    ],
    citas: [
      {
        id: 'cita-401',
        pacienteNombre: 'Adriana Ortiz',
        motivoConsulta: 'Consulta Neurológica',
        diaAbrev: 'LUN',
        fecha: '2026-08-10',
        horaInicio: '09:00',
        horaFin: '10:00',
        estado: 'Atendida',
        consultorio: 'Consultorio 410',
      },
      {
        id: 'cita-402',
        pacienteNombre: 'Diego Navarro',
        motivoConsulta: 'Electroencefalograma (EEG)',
        diaAbrev: 'MIÉ',
        fecha: '2026-08-12',
        horaInicio: '11:00',
        horaFin: '12:30',
        estado: 'Confirmada',
        consultorio: 'Consultorio 410',
      },
      {
        id: 'cita-403',
        pacienteNombre: 'Valeria Rivas',
        motivoConsulta: 'Evaluación Cefalea Crónica',
        diaAbrev: 'VIE',
        fecha: '2026-08-14',
        horaInicio: '16:00',
        horaFin: '17:00',
        estado: 'Confirmada',
        consultorio: 'Consultorio 410',
      },
    ],
  },
  {
    id: 'prof-5',
    nombre: 'Carlos',
    apellido: 'Ruiz',
    tituloPrefix: 'Dr.',
    especialidad: 'Medicina General',
    subespecialidad: 'Medicina General',
    registroProfesional: 'CMP-29401',
    consultorio: 'Consultorio 102',
    estado: 'Activo',
    citasHoy: 6,
    disponibleHoy: true,
    foto: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80',
    telefono: '+51 987 778 899',
    email: 'cruiz@healtlab.com',
    disponibilidad: [
      { dia: 'LUN', diaNombre: 'Lunes', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: true },
      { dia: 'LUN', diaNombre: 'Lunes', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: true },
      { dia: 'MAR', diaNombre: 'Martes', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: true },
      { dia: 'MAR', diaNombre: 'Martes', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: true },
      { dia: 'MIÉ', diaNombre: 'Miércoles', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: true },
      { dia: 'MIÉ', diaNombre: 'Miércoles', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: true },
      { dia: 'JUE', diaNombre: 'Jueves', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: true },
      { dia: 'JUE', diaNombre: 'Jueves', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: true },
      { dia: 'VIE', diaNombre: 'Viernes', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: true },
      { dia: 'VIE', diaNombre: 'Viernes', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: true },
      { dia: 'SÁB', diaNombre: 'Sábado', jornada: 'Mañana', horaInicio: '09:00', horaFin: '12:00', activo: false },
      { dia: 'SÁB', diaNombre: 'Sábado', jornada: 'Tarde', horaInicio: '14:00', horaFin: '17:00', activo: false },
      { dia: 'DOM', diaNombre: 'Domingo', jornada: 'Mañana', horaInicio: '08:00', horaFin: '13:00', activo: false },
      { dia: 'DOM', diaNombre: 'Domingo', jornada: 'Tarde', horaInicio: '14:00', horaFin: '18:00', activo: false },
    ],
    citas: [
      {
        id: 'cita-501',
        pacienteNombre: 'Fernando Meléndez',
        motivoConsulta: 'Evaluación Hipertensión',
        diaAbrev: 'LUN',
        fecha: '2026-08-10',
        horaInicio: '08:00',
        horaFin: '09:00',
        estado: 'Atendida',
        consultorio: 'Consultorio 102',
      },
      {
        id: 'cita-502',
        pacienteNombre: 'Patricia Flores',
        motivoConsulta: 'Consulta General',
        diaAbrev: 'MIÉ',
        fecha: '2026-08-12',
        horaInicio: '10:00',
        horaFin: '11:00',
        estado: 'Confirmada',
        consultorio: 'Consultorio 102',
      },
    ],
  },
];
